spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/redis
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  data:
    redis:
      host: localhost
      port: 6379

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  jwt-key: "LMRLvJVDp/lUVRG6EcJTo7g6moHepHps9lRFw9KIiA4="
